routes/web.php
<?php

use App\Location;
use Illuminate\Support\Facades\Auth;

Route::get('/', function () {

    if (Auth::check()) {
        $location = Location::first();

        if (isset($location)) {
            return redirect('dashboard/' . $location->id);
        } else {
            return redirect('location/create');
        }
    }
    return view('auth.login');
});

Route::get('/home', function () {
    return redirect('/');
});



/*
Iz rute je izbacen da ne bi prikazivao registraciju korisnika
\vendor\laravel\framework\src\Illuminate\Routing\Router.php
line: 306, 307
 */


Route::get('dashboard/{location_id}', 'HomeController@index');
Route::resource('profile', 'ProfileController');
Route::post('/profile/{id}/roles', 'ProfileController@UpdateRoles');
Route::patch('profile/{profile}/password', 'ProfileController@update_password');
Route::post('profile/{profile}', 'ProfileController@update_avatar');

Auth::routes();

Route::resource('message', 'MessageController');
// Route::get('events', 'EventController@index');

Route::get('logout', '\App\Http\Controllers\Auth\LoginController@logout');

// // Rute za manipulaciju sa roditeljima
// Route::resource('parent', 'ParentController');

//ADMINISTRATOR prava pristupa
Route::group(['middleware' => ['auth', 'role:admin']], function () {

// Route::get('search', 'AdministratorStudentController@search');

    // Rute za manipulaciju sa polaznicima
    Route::resource('administrator/student', 'AdministratorStudentController');
    Route::delete('administrator/student/subject/{id}', 'AdministratorStudentController@subject_destroy')
        ->name('student.subject_destroy');
    Route::put('administrator/student/subject/{id}', 'AdministratorStudentController@subject_update')
        ->name('student.subject_update');
    Route::post('administrator/student/subject', 'AdministratorStudentController@subject_store')
        ->name('student.subject_store');
    Route::get('administrator/student/{id}/pdf/prijava', 'AdministratorStudentController@PdfPrijava')
        ->name('student.prijava');

    // Rute za manipulaciju sa nastavnicima
    Route::resource('administrator/teacher', 'AdministratorTeacherController');
    Route::get('administrator/teacher/pdf/spisak', 'AdministratorTeacherController@PdfSpisakPredavaca')
        ->name('teacher.spisak');
    Route::get('administrator/teacher/{id}/pdf/prijava', 'AdministratorTeacherController@PdfPrijava')
        ->name('teacher.prijava');
    Route::get('administrator/teacher/pdf/ugovor', 'AdministratorTeacherController@PdfUgovor')
        ->name('teacher.ugovor');

    // Rute za manipulaciju sa uslugama
    Route::resource('administrator/service', 'AdministratorServiceController');

    // Rute za manipulaciju sa kategorijama usluga
    Route::resource('administrator/category', 'AdministratorCategoryController');

    // Rute za manipulaciju sa kursevi
    Route::resource('administrator/course', 'AdministratorCourseController');
    Route::get('/findServices', 'AdministratorCourseController@findServices');
    Route::post('administrator/course/findStudent', 'AdministratorCourseController@findStudent')
        ->name('course.findStudent');
    Route::get('administrator/course/addStudent/{id}/{course_id}', 'AdministratorCourseController@addStudent')
        ->name('course.addStudent');
    Route::get('administrator/course/deleteStudent/{id}/{course_id}', 'AdministratorCourseController@deleteStudent')
        ->name('course.deleteStudent');
    Route::post('administrator/course/changePrice', 'AdministratorCourseController@changePrice')
        ->name('course.changePrice');     

    Route::resource('admin', 'AdminController');

    Route::resource('event', 'EventController');
    Route::post('event/attend', 'EventController@attend')
        ->name('event.attend');

    Route::resource('location', 'LocationController');

});

resources/views/administrators/courses/create.blade.php
@extends('layouts.app')

@section('htmlheader_title')
    Unos novog kursa
@endsection

@section('contentheader_title')
    Unos novog kursa
@endsection

@section('header-extra')
<!-- parsley CSS -->
{!! Html::style('/css/parsley.css') !!}
    {!! Html::style('/plugins/datepicker/datepicker3.css') !!}
    {{-- {!! Html::style('/plugins/timepicker/bootstrap-timepicker.css') !!} --}}
    {!! Html::style('//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css') !!}

@endsection

@section('main-content')
    {!! Form::open(['route' => 'course.store', 'class' => 'form-signin', 'data-parsley-validate' ]) !!}
        @include('administrators.courses._form')     
    {!! Form::close() !!}   
@endsection

@section('scripts-extra')
<script type="text/javascript">
    window.ParsleyConfig = {
            errorsWrapper: '<div></div>',
            errorTemplate: '<span class="error-text"></span>',
            classHandler: function (el) {
                return el.$element.closest('input');
            },
            successClass: 'valid',
            errorClass: 'invalid'
        };

        $('.category_id').change(function(){
            var cat_id=$(this).val();
            var opS=" ";
            var opT=" ";

            $.ajax({
                type:'get',
                url:'{!!URL::to('findServices')!!}',
                data:{
                        'id':cat_id,
                        '_token': $('input[name=_token]').val()
                },

                success:function(data){
                    if (data.services.length > 0) {
                            for(var i=0;i<data.services.length;i++){
                            opS+='<option value="'+data.services[i].id+'">'+data.services[i].naziv+'</option>';
                            }
                    }else {
                            opS='<option value="'+'0'+'">'+'Nema podataka'+'</option>';
                        }
                    $('.service_id').html(" ");
                    $('.service_id').append(opS);
                    if (data.teachers.length > 0 && data.services.length > 0) {
                            for(var i=0;i<data.teachers.length;i++){
                            opT+='<option value="'+data.teachers[i].id+'">'+data.teachers[i].ime+ " " +data.teachers[i].prezime+'</option>';
                            }
                    }else {
                            opT='<option value="'+'0'+'">'+'Nema podataka'+'</option>';
                        }
                    $('.teacher_id').html(" ");
                    $('.teacher_id').append(opT);
                },
                error:function(){
                }
            });
        });
</script>
<script type="text/javascript">
    $(function () {
            $( "input[id$='date']" ).datepicker({
             format: "dd.mm.yyyy.",
             language: "rs-latin"
            });
          });
</script>
<script type="text/javascript">
    $(function () {        
            $( "input[id$='time']" ).timepicker({
                timeFormat: 'HH:mm',
                interval: 15,
                minTime: '7',
                maxTime: '10:00pm',
                defaultTime: '7',
                // startTime: '7:00',
                dynamic: false,
                dropdown: true,
                scrollbar: true
            });  
          });
</script>
<!-- parsley JS-->
{!! Html::script('/js/parsley.min.js') !!}
    {!! Html::script('/js/rs.js') !!}
    {!! Html::script('/plugins/datepicker/bootstrap-datepicker.js') !!}
    {{-- {!! Html::script('/plugins/timepicker/bootstrap-timepicker.js') !!} --}}
    {!! Html::script('//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js') !!}
    {!! Html::script('/plugins/ckeditor/ckeditor.js') !!} 

@endsection

resources/views/administrators/courses/findStudent.blade.php
@extends('layouts.app')

@section('htmlheader_title')
    Pretraga polaznika
@endsection

@section('contentheader_title')
    Pretraga polaznika
@endsection


@section('header-extra')

@endsection


@section('main-content')


 <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Prikaz svih polaznika</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="example" class="table table-hover table-condensed table-striped">
                            <thead>
                                {{-- <th>R.br.</th> --}}
                                <th>Ime i prezime</th>
                                <th>Razred</th>
                                <th>Predmet</th>
                                <th>Datum rođenja</th>
                                <th>Telefon</th>
                                <th>Adresa</th>
                                {{-- <th>Kurs</th> --}}
                                {{-- <th>Balans</th> --}}
                                <th> </th>
                            </thead>

                            <tbody>
                                @php
                                    // $i = ($students->currentPage()-1)*$students->perPage();
                                @endphp
                                
                                @foreach ($students as $student)

                                    <tr id='{{ $student->id }}'>
                                        {{-- <td>{{ ++$i }}.</td> --}}
                                        <td> <a href="{{ route('student.show', $student->id) }}" title="Prikaži detalje">{{ $student->ime }} {{ $student->prezime }}</a></td>
                                        <td> {{ $student->razred}} </td>  
                                        <td> 
                                            @foreach ($student->subjects as $subject)
                                                <ul>
                                                    <li> {{$subject->name}} </li>
                                                </ul>
                                            @endforeach
                                        </td>  

                                        <td> {{ date('d.m.Y.', strtotime( $student->rodjen)) }} </td>
                                        <td> {{ $student->telefon}} </td>
                                        <td> {{ $student->adresa}} </td>  
                                        {{-- <td> </td> --}}
                                        {{-- <td></td> --}}
                                        <td class="td" align="right" style="width:100px">
                                            <form action="/administrator/course/addStudent" method="POST">
                                                {{ csrf_field() }}
                                                <a href="{{ route('course.addStudent', [ $student->id, $course->id]) }}"  class="btn " title="Dodaj polaznika"><i class="fa fa-check"></i></a> 
                                            </form>
                                        </td>
                                    </tr>
                                    
                                @endforeach

                            </tbody>  

                        </table>

                        <div class="text-center">
                            {{-- {!! $students->links(); !!}                 --}}
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>

{{--     <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Rezultat pretrage polaznika</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="example" class="table table-hover table-condensed table-striped">
                            <thead>
                                <th>Ime i prezime</th>
                                <th>Datum rođenja</th>
                                <th>Telefon</th>
                                <th>Adresa</th>
                                {{-- <th>Kurs</th> --}}
{{--                                 <th> </th>
                            </thead>

                            <tbody>

                                
                                @foreach ($students as $student)

                                    <tr id='{{ $student->id }}'>
                                        <td> {{ $student->ime }} {{ $student->prezime }} </td>
                                        <td> {{ date('d.m.Y.', strtotime( $student->rodjen)) }} </td>
                                        <td> {{ $student->telefon}} </td>
                                        <td> {{ $student->adresa}} </td>  
                                        {{-- <td></td> --}}
{{--                                         <td class="td" align="right" style="width:200px">
                                            <form action="/administrator/course/addStudent" method="POST">
                                                {{ csrf_field() }}
                                                <a href="{{ route('course.addStudent', [ $student->id, $course->id]) }}"  class="btn " title="Dodaj polaznika"><i class="fa fa-check"></i></a> 
                                            </form>     
                                        </td>
                                    </tr>

                                @endforeach

                            </tbody>  
                        </table>

                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div> --}} 


@endsection

@section('scripts-extra')

    <script type="text/javascript">

        $(document).ready(function() {
            $('#example').DataTable({
                "language": {
                "url": "//cdn.datatables.net/plug-ins/1.10.13/i18n/Serbian.json"
                },
                "bPaginate": false,
                "bLengthChange": false,
                "bFilter": true,
                "bInfo": false,
                "bAutoWidth": false                
            });
        } );
        
     </script>

@endsection

resources/views/administrators/courses/index.blade.php
@extends('layouts.app')

@section('htmlheader_title')
    Termini
@endsection

@section('contentheader_title')
    Termini
@endsection

@section('header-extra')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css"/>
@endsection

@section('main-content')

    <div class="box">
        <div class="box-header with-border">
            <h3 class="box-title">Prikaz svih termina</h3>
        </div>
        <div class="box-body">
            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="example" class="table table-hover table-condensed table-striped">
                            <thead>
                                <th>R.br.</th>
                                <th>Usluga</th>
                                <th>Kategorija</th>
                                <th>Početak</th>
                                <th>Kraj</th>
                                <th>Vreme</th>
                                <th>Predavač</th>
                                <th>Lokacija</th>
                                <th>Pon.</th>
                                <th>Uto.</th>
                                <th>Sre.</th>
                                <th>Čet.</th>
                                <th>Pet.</th>
                                <th>Sub.</th>
                                <th>Ned.</th>
                                <th> </th>
                            </thead>

                            <tbody>

                                @php
                                    $i = ($courses->currentPage()-1)*$courses->perPage();
                                @endphp

                                @foreach ($courses as $course)
                                    <tr>
                                        <td> {{ ++$i }}.</td>
                                        <td> <a href="{{ route('service.edit', $course->service_id) }}"> {{ $course->service->naziv or '' }} </a></td>
                                        <td> {{ $course->service->category->naziv or '' }} </td>
                                        <td> {{ date('d.m.Y.', strtotime($course->start_date)) }} </td>
                                        <td> {{ date('d.m.Y.', strtotime($course->end_date)) }} </td>
                                        <td> {{ date('H:i', strtotime($course->start_time)) }} - {{date('H:i', strtotime($course->end_time))}} </td>
                                        <td> <a href="{{ route('teacher.edit', $course->teacher_id) }}"> {{ $course->teacher->ime }} {{$course->teacher->prezime }}</a></td>
                                        <td> <a href="{{ route('location.edit', $course->location_id) }}"> {{ $course->location->name }} </a></td>
                                        <td> {!! isset($course->mon) ? "<p align='center'><i class='fa fa-check'></i></p>" : ''!!} </td>
                                        <td> {!! isset($course->tue) ? "<p align='center'><i class='fa fa-check'></i></p>" : ''!!} </td>
                                        <td> {!! isset($course->wed) ? "<p align='center'><i class='fa fa-check'></i></p>" : ''!!} </td>
                                        <td> {!! isset($course->thu) ? "<p align='center'><i class='fa fa-check'></i></p>" : ''!!} </td>
                                        <td> {!! isset($course->fri) ? "<p align='center'><i class='fa fa-check'></i></p>" : ''!!} </td>
                                        <td> {!! isset($course->sat) ? "<p align='center'><i class='fa fa-check'></i></p>" : ''!!} </td>
                                        <td> {!! isset($course->sun) ? "<p align='center'><i class='fa fa-check'></i></p>" : ''!!} </td>

                                        <td class="td" align="right" style="width:150px">
                                            
                                            <a href="{{ route('course.show', $course->id) }}"  class="btn" title="Prikaz trmina"><i class="fa fa-eye"></i></a> 
                                            <a href="{{ route('course.edit', $course->id) }}"  class="btn " title="Izmeni termina"><i class="fa fa-pencil-square-o"></i></a> 
                                            <a class="btn" data-course_id="{{ $course->id }}" data-course_name="{{ $course->name }}"  data-toggle="modal" data-target="#confirmDelete" title="Izbriši termin"><i class="fa fa-trash-o"></i></a> 
                                        </td>
                                    </tr>
                                @endforeach

                            </tbody>  

                        </table>

                        <div class="text-center">
                            {!! $courses->links(); !!}                
                        </div>

                    </div>
                </div>
            </div>
        </div>
        <!-- /.box-body -->
    </div>
<!--  -->
    <div class="modal fade" id="confirmDelete" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Potvrda brisanja termina</h4>
              </div>
              <div class="modal-body">
                <p>Da li ste sigurni da želite obrisati odabrani Termin?</p>
              </div>
              <div class="modal-footer">
                {!! Form::open(['method' => 'DELETE', 'id'=>'delForm']) !!}
                    <button type="button" class="btn btn-default" data-dismiss="modal">Odustani</button>
                    <button type="submit" class="btn btn-primary">Izbriši</button>
                {!! Form::close() !!}
              </div>
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal --> 


@endsection

@section('scripts-extra')
    <script type="text/javascript">

        $('#confirmDelete').on('show.bs.modal', function(e) {
            var courseId = $(e.relatedTarget).data('course_id');
            $("#delForm").attr('action', 'course/'+courseId);
        });

        $(document).ready(function() {
        $('#example').DataTable({
            "language": {
            "url": "//cdn.datatables.net/plug-ins/1.10.13/i18n/Serbian.json"
            },
            "bPaginate": false,
            "bLengthChange": false,
            "bFilter": true,
            "bInfo": false,
            "bAutoWidth": false
        });
        } );    
        
    </script>
@endsection

resources/views/administrators/courses/show.blade.php
@extends('layouts.app')

@section('htmlheader_title')
    Prikaz kursa
@endsection

@section('contentheader_title')
    Prikaz kursa
@endsection

@section('header-extra')
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.css"/>

@endsection

@section('main-content')

<div class="row">
    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h2 class="box-title">{{$course->service->category->naziv}} - {{$course->service->naziv}} (događaja: {{$countEvents}})</h2>
            </div>
            <div class="box-body">
                <div class="row col-md-6">
                    <h4><ins>Kurs</ins></h4>
                    <p>Kategorija: <STRONG> {{$course->service->category->naziv}} </STRONG></p>
                    <p>Usluga: <STRONG> {{$course->service->naziv}} </STRONG></p>
                    <p>Cena usluge: <STRONG> {{number_format($course->service->cena, 2, ',', '.')}} RSD</STRONG></p>
                    <br>
                </div> 

                <div class="row col-md-6">
                    <h4><ins>Predavač</ins></h4>
                    <p>Ime i prezime: <STRONG> {{$course->teacher->ime or ''}} {{$course->teacher->prezime or ''}} </STRONG></p>
                    <p>Kontakt telefon: <STRONG> {{$course->teacher->telefon or ''}} </STRONG></p>
                    <p>E-mail: <STRONG> {{$course->teacher->email or ''}} </STRONG></p>
                    <br>
                </div> 

                <div class="row col-md-6">
                    <h4><ins>Lokacija realizacije</ins></h4>
                    <p>Naziv lokacije: <STRONG> {{$course->location->name}} </STRONG></p>
                    <p>Adressa lokacije: <STRONG> {{$course->location->address}} </STRONG></p>
                    <p>Kapacitet lokacije: <STRONG> {{$course->location->capacity}} polaznika</STRONG></p>
                    <br>
                </div> 

                <div class="row col-md-6">
                    <h4><ins>Period realizacije</ins></h4>
                    <p>Početka realizacije: <STRONG> {{Carbon::parse($course->start_date)->format('d.m.Y.') }}  godine</STRONG></p>
                    <p>Kraj realizacije: <STRONG> {{Carbon::parse($course->end_date)->format('d.m.Y.') }}   godine</STRONG></p>
                    <p>U terminu od <STRONG> {{$course->start_time}} </STRONG> do <STRONG>{{$course->end_time}}</STRONG></p>
                </div> 
        
            <div class="row">
            <div class="col-md-12">
                <div class="box-header with-border">
                    <h2 class="box-title"><ins>Polaznici</ins></h2>
                    <form action="/administrator/course/findStudent" method="POST" role="search">
                        {{ csrf_field() }}
                        {{ Form::hidden('course_id', $course->id) }}
                         <button type="submit" class="pull-right btn btn-default btn-sm"><span class="glyphicon glyphicon-search"></span></button>
                    </form>            
                </div>
            </div>
            </div>
  

            <div class="row">
                <div class="col-md-12">
                    <div class="table-responsive">
                        <table id="example" class="table table-hover table-condensed table-striped">
                            <thead>
                                <th>Ime i prezime</th>
                                <th>Razred</th>
                                <th>Predmet</th>
                                <th>Datum rođenja</th>
                                <th>Telefon</th>
                                <th>Adresa</th>
                                <th>Cena</th>
                                <th> </th>
                            </thead>

                            <tbody>
                                
                                @foreach ($course->students as $student)

                                    <tr id='{{ $student->id }}'>

                                        <td> <a href="{{ route('student.show', $student->id) }}" title="Prikaži detalje">{{ $student->ime }} {{ $student->prezime }}</a></td>
                                        <td> {{ $student->razred}} </td>  
                                        <td> 
                                            @foreach ($student->subjects as $subject)
                                                    {{$subject->name}} 
                                            @endforeach
                                        </td>  
                                        <td> {{ date('d.m.Y.', strtotime( $student->rodjen)) }} </td>
                                        <td> {{ $student->telefon }} </td>
                                        <td> {{ $student->adresa }} </td>  
                                        <td>
                                        <a href="#" 
                                          data-price="{{number_format($student->pivot->price, 2, ',', '.')}}" 
                                          data-student_id="{{ $student->id }}"  
                                          data-course_id="{{ $course->id }}"  
                                          data-toggle="modal" 
                                          data-target="#editPrice""> {{number_format($student->pivot->price, 2, ',', '.')}} RSD
                                        </a>
                                      </td>
                                      <td class="td" align="right" style="width:100px">
                                          <a href="{{ route('student.show', $student->id) }}" class="btn-sm btn" title="Izbrisi polaznika"><i class="fa fa-eye"></i></a> 

                                          <a href="{{ route('course.deleteStudent', [$student->id, $course->id]) }}" class="btn btn-sm" title="Izbrisi polaznika"><i class="fa fa-trash"></i></a> 
                                      </td>
                                    </tr>
                                    
                                @endforeach

                            </tbody>  

                        </table>

                    </div>
                </div>
            </div>


        </div>
 
        </div> 
    </div> 



    <div class="col-md-6">
        <div class="box box-primary">
            <div class="box-header with-border">
                <h3 class="box-title">Događaji</h3>
            </div>
            <div class="box-body">
                <div class="row col-md-12">
                    <div id="calendar" class="fc fc-unthemed fc-ltr"> </div>
                </div> 
            </div> 
        </div> 
    </div>    
</div> <!-- end of .row -->


    {{-- MODAL EDIT CENA --}}
    <div class="modal fade" id="editPrice" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
              <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                <h4 class="modal-title">Izmena cene</h4>
              </div>
              {!! Form::open(['route' => 'course.changePrice', 'class' => 'form-signin', 'data-parsley-validate' ]) !!}
                <div class="modal-body">
                  <p>Unesite ovi iznos koji plaća polaznik.</p>
                    <div class="row">
                      <div class="col-sm-4">
                  
                      {{Form::hidden('student_id', null, 
                            [
                            'class'=> 'form-control form-group',
                            'id'=> 'student_id'
                            ])
                        }}
                        {{Form::hidden('course_id', null, 
                            [
                            'class'=> 'form-control form-group',
                            'id'=> 'course_id'
                            ])
                        }}
                        {{Form::text('amount', null, 
                            [
                            'class'=> 'form-control form-group',
                            'id'=> 'amount',
                            'placeholder' => 'iznos...',
                            'required' => '', 
                            ])
                        }}
                      </div>
                    </div>
                </div>
                <div class="modal-footer">
                      <button type="button" class="btn btn-default" data-dismiss="modal">Odustani</button>
                      <button type="submit" class="btn btn-primary">Prihvati</button>
                </div>
              {!! Form::close() !!}
            </div><!-- /.modal-content -->
        </div><!-- /.modal-dialog -->
    </div><!-- /.modal --> 
   
@endsection

@section('scripts-extra')
    <script src="https://cdnjs.cloudflare.com/ajax/libs/fullcalendar/3.4.0/fullcalendar.min.js"></script>
    <script src="{{ asset('plugins/fullcalendar/locale/sr.js') }}" type="text/javascript"></script>
 <script>

        $(document).ready(function() {
           var $calendar = $('#calendar').fullCalendar(
            {   
                snapDuration: '00:15:00',
                editable: true,
                minTime: "07:00:00",
                maxTime: "22:00:00",
               // contentHeight: 800,
                header: {
                    left: 'today',
                    center: 'title',
                    // right: 'listMonth, month,agendaWeek prev,next'
                    right: 'prev,next'
                    },
                defaultView: 'listMonth',
                events: [

                        @foreach($course->events as $event)
                        {
                            id : '{{ $event->id }}',
                            title : '{{ $event->title }}  xxx',
                            start : '{{ $event->start }}',
                            end : '{{ $event->end }}',
                            color: '{{ $event->background_color }}'
                        },
                        @endforeach
                ],
            });
        });


        $('#editPrice').on('shown.bs.modal', function(e) {
            var price = $(e.relatedTarget).data('price');
            var course_id = $(e.relatedTarget).data('course_id');
            var student_id = $(e.relatedTarget).data('student_id');
            var modal = $(this);
            modal.find('#student_id').val(student_id);
            modal.find('#course_id').val(course_id);
            modal.find('#amount').val(price);

        });

    </script>
@endsection